# This file is part of Simjit project <https://simjit.org>
#
# See LICENSE for license and copyright information
# SPDX-License-Identifier: Zlib

from __future__ import annotations

# Native extension signatures are generated by pybind11-stubgen and remain partially
# unknown at this boundary.
# pyright: reportUnknownArgumentType=false, reportUnknownMemberType=false
# pyright: reportUnknownVariableType=false
import dataclasses
from collections.abc import Mapping
from typing import Literal, Protocol, cast, runtime_checkable

from . import _simjit, dataframe, ir

OutputKind = Literal["numpy", "pyarrow"]


class _Indexable(Protocol):
    def __len__(self) -> int: ...

    def __getitem__(self, index: int, /) -> object: ...


@runtime_checkable
class _HasItem(Protocol):
    def item(self) -> object: ...


class Result(Mapping[str, object]):
    def __init__(self, data: Mapping[str, object]):
        self._data: dict[str, object] = dict(data)

    def __getitem__(self, key: str) -> object:
        return self._data[key]

    def __iter__(self):
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def __getattr__(self, name: str) -> object:
        try:
            return self._data[name]
        except KeyError:
            raise AttributeError(name) from None

    def __repr__(self) -> str:
        return f"Result({self._data!r})"

    def to_dict(self) -> dict[str, object]:
        return dict(self._data)


@dataclasses.dataclass(frozen=True)
class InspectionResult:
    hir: str
    serialized: str
    vectorizer: str
    vectorization_exception: str
    mir: str
    asmjit_compile_us: float | None
    asm: str
    cpp: str
    llvm_ir: str
    diagnostics: tuple[str, ...]

    @property
    def asm_code(self) -> str:
        return self.asm


def _inspection_result(raw: Mapping[str, object]) -> InspectionResult:
    asmjit_compile_us = raw.get("asmjit_compile_us")
    if isinstance(asmjit_compile_us, (int, float)):
        asmjit_compile_us = float(asmjit_compile_us)
    elif asmjit_compile_us is not None:
        raise TypeError("asmjit_compile_us must be numeric or None")
    raw_diagnostics = raw.get("diagnostics", ())
    if not isinstance(raw_diagnostics, (list, tuple)):
        raise TypeError("diagnostics must be a list or tuple")
    return InspectionResult(
        hir=str(raw.get("hir", "")),
        serialized=str(raw.get("serialized", "")),
        vectorizer=str(raw.get("vectorizer", "")),
        vectorization_exception=str(raw.get("vectorization_exception", "")),
        mir=str(raw.get("mir", "")),
        asmjit_compile_us=asmjit_compile_us,
        asm=str(raw.get("asm_code", "")),
        cpp=str(raw.get("cpp", "")),
        llvm_ir=str(raw.get("llvm_ir", "")),
        diagnostics=tuple(str(item) for item in raw_diagnostics),
    )


def _program_outputs(program: dataframe.Program) -> list[tuple[str, ir.Expr]]:
    return program.to_dsl()


def _validate_buffer_handle_mapping(
    name: str,
    value: Mapping[str, ir.BufferHandle],
) -> dict[str, ir.BufferHandle]:
    result = dict(value)
    for key, handle in result.items():
        if not isinstance(key, str):
            raise TypeError(f"{name} keys must be strings")
        if not isinstance(handle, ir.BufferHandle):
            raise TypeError(f"{name}[{key!r}] must be an ir.BufferHandle")
    return result


def _validate_output_names(
    outputs: Mapping[str, ir.BufferHandle],
    output_graph: list[tuple[str, ir.Expr]],
) -> None:
    expected = {name for name, _ in output_graph}
    actual = set(outputs)
    missing = expected - actual
    extra = actual - expected
    if missing:
        raise ValueError(f"missing output buffer(s): {', '.join(sorted(missing))}")
    if extra:
        raise ValueError(f"unexpected output buffer(s): {', '.join(sorted(extra))}")


def run_program(
    program: dataframe.Program,
    inputs: Mapping[str, object],
    *,
    output: OutputKind = "numpy",
    session: _simjit.Session | None = None,
) -> Result:
    outputs = _program_outputs(program)

    if session is None:
        raw = _simjit.run_program(outputs, inputs, output)
    else:
        raw = session.run_program(outputs, inputs, output)
    return Result(cast(Mapping[str, object], raw))


def inspect(
    program: dataframe.Program,
    schema: Mapping[str, ir.ScalarType | tuple[ir.ScalarType, bool]],
    *,
    output: OutputKind = "numpy",
    policy: str = "best_effort",
    arch: str = "native",
) -> InspectionResult:
    raw = _simjit.inspect_schema(
        _program_outputs(program),
        schema,
        output,
        policy,
        arch,
    )
    return _inspection_result(cast(Mapping[str, object], raw))


def inspect_serialized(
    serialized: str,
    *,
    policy: str = "best_effort",
    arch: str = "native",
) -> InspectionResult:
    raw = _simjit.inspect_serialized(serialized, policy, arch)
    return _inspection_result(cast(Mapping[str, object], raw))


class PreparedRunner:
    def __init__(self, prepared: _simjit.PreparedProgram, session: _simjit.Session):
        self._prepared: _simjit.PreparedProgram = prepared
        self._session: _simjit.Session = session
        raw_outputs = cast(Mapping[str, object], prepared.output_buffers())
        self._outputs: Result = Result(raw_outputs)

    @property
    def identifier(self) -> str:
        return self._prepared.identifier

    @property
    def outputs(self) -> Result:
        return self._outputs

    def run(self, inputs: Mapping[str, object] | None = None) -> None:
        if inputs is None:
            self._prepared.run()
        else:
            self._prepared.run(inputs)

    def result(self) -> Result:
        raw = cast(Mapping[str, object], self._prepared.result())
        return Result(raw)

    def scalar(self, name: str) -> object:
        value = cast(_Indexable, self._outputs[name])
        try:
            length = len(value)
        except TypeError as exc:
            raise TypeError(
                f"output {name!r} is not an indexable scalar buffer"
            ) from exc
        if length != 1:
            raise ValueError(
                f"output {name!r} has length {length}, expected scalar length 1"
            )

        item = value[0]
        if isinstance(item, _HasItem):
            return item.item()
        return item

    def scalars(self) -> dict[str, object]:
        return {name: self.scalar(name) for name in self._outputs}


def prepare_program(
    program: dataframe.Program,
    example_inputs: Mapping[str, object],
    *,
    output: OutputKind = "numpy",
    session: _simjit.Session | None = None,
) -> PreparedRunner:
    if output != "numpy":
        raise ValueError("prepare_program currently supports output='numpy' only")
    if session is None:
        session = _simjit.Session()
    prepared = session.prepare_program(
        _program_outputs(program), example_inputs, output
    )
    return PreparedRunner(prepared, session)


def run_into(
    program: dataframe.Program,
    inputs: Mapping[str, ir.BufferHandle],
    outputs: Mapping[str, ir.BufferHandle],
    *,
    n: int | None = None,
    session: _simjit.Session | None = None,
) -> Result:
    input_handles = _validate_buffer_handle_mapping("inputs", inputs)
    output_handles = _validate_buffer_handle_mapping("outputs", outputs)
    output_graph = _program_outputs(program)
    _validate_output_names(output_handles, output_graph)

    collisions = set(input_handles) & set(output_handles)
    if collisions:
        raise ValueError(
            f"input/output buffer name collision: {', '.join(sorted(collisions))}"
        )

    buffers = {**input_handles, **output_handles}
    if n is None:
        n = _simjit._infer_native_length(buffers, output_graph)

    if session is None:
        _simjit.run_native(buffers, output_graph, n)
    else:
        session.run_native(buffers, output_graph, n)
    return Result({name: handle.buf for name, handle in output_handles.items()})
