#!/usr/bin/env python3
# This file is part of Simjit project <https://simjit.org>
#
# See LICENSE for license and copyright information
# SPDX-License-Identifier: Zlib

#
# Use this script to objdump raw machine code generated by asmjit in tests.jsonl.
# It was created because sometimes asmjit asm output does not match machine code output.
# Or more frequently: asm output shows that instructions were emitted, but in x86 ISA there are no
# encodings for them - and objdump will show invalid disasm.

import argparse
import base64
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ASM_CODE_NAMES = ("asmjit", "asmjit_s")


ARCH_CONFIG = {
    "x86": {
        "target": "x86_64-pc-linux-gnu",
        "objdump_options": ["-M", "intel"],
    },
    "arm": {
        "target": "aarch64-linux-gnu",
        "objdump_options": [],
    },
}


def fail(message: str) -> None:
    print(f"objdump-asmjit-json: {message}", file=sys.stderr)
    sys.exit(1)


def need_tool(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        fail(f"missing required command: {name}")
    return path


def sanitize_symbol(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not name or name[0].isdigit():
        name = f"sym_{name}"
    return name


def load_jsonl_item(
    path: Path,
    n: int | None,
    test_id: str | None,
    suite: str | None,
    variant: str | None,
) -> dict:
    matches = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            if n is not None and item.get("n") != n:
                continue
            if test_id is not None and item.get("id") != test_id:
                continue
            if suite is not None and item.get("suite") != suite:
                continue
            if variant is not None and item.get("variant") != variant:
                continue
            item["_jsonl_line"] = line_no
            matches.append(item)

    if not matches:
        criteria = []
        if n is not None:
            criteria.append(f"n={n}")
        if test_id is not None:
            criteria.append(f"id={test_id}")
        if suite is not None:
            criteria.append(f"suite={suite}")
        if variant is not None:
            criteria.append(f"variant={variant}")
        fail(f"no item found in {path} for {', '.join(criteria) or 'first item'}")
    if len(matches) > 1:
        fail(
            f"{len(matches)} items match; add --n, --id, --suite, or --variant to disambiguate"
        )
    return matches[0]


def code_entries(item: dict, code_name: str | None, all_asmjit: bool) -> list[dict]:
    codes = item.get("codes", [])
    if all_asmjit:
        result = [c for c in codes if c.get("name") in ASM_CODE_NAMES]
    else:
        wanted = code_name or "asmjit"
        result = [c for c in codes if c.get("name") == wanted]
    if not result:
        available = ", ".join(c.get("name", "?") for c in codes)
        fail(f"requested code not found; available code names: {available}")
    return result


def detect_arch(item: dict) -> str:
    variant = str(item.get("variant", ""))
    if variant.startswith("x86-") or variant == "x86":
        return "x86"
    if variant.startswith("arm-") or variant == "arm":
        return "arm"
    fail(
        f"cannot detect arch from item variant={variant!r}; use --arch x86 or --arch arm"
    )


def resolve_arch_config(
    item: dict, arch: str, target: str | None
) -> tuple[str, str, list[str]]:
    resolved_arch = detect_arch(item) if arch == "auto" else arch
    if resolved_arch not in ARCH_CONFIG:
        fail(f"unsupported arch: {resolved_arch}")
    config = ARCH_CONFIG[resolved_arch]
    return resolved_arch, target or config["target"], list(config["objdump_options"])


def write_executable_object(
    raw: bytes,
    symbol: str,
    work_dir: Path,
    clang: str,
    target: str,
    arch: str,
) -> tuple[Path, Path, Path]:
    bin_path = work_dir / f"{symbol}.bin"
    asm_path = work_dir / f"{symbol}.s"
    obj_path = work_dir / f"{symbol}.o"

    bin_path.write_bytes(raw)
    escaped_bin = str(bin_path).replace("\\", "\\\\").replace('"', '\\"')
    lines = [".text"]
    if arch == "arm":
        lines.append("$x:")
    lines.extend(
        [
            f".globl {symbol}",
            f".type {symbol},@function",
            f"{symbol}:",
            f'.incbin "{escaped_bin}"',
            "",
        ]
    )
    asm_path.write_text("\n".join(lines), encoding="utf-8")

    subprocess.run(
        [clang, "-target", target, "-c", str(asm_path), "-o", str(obj_path)],
        check=True,
    )
    return bin_path, asm_path, obj_path


def objdump(
    obj_path: Path, llvm_objdump: str, show_raw: bool, objdump_options: list[str]
) -> str:
    cmd = [llvm_objdump, "-d", *objdump_options]
    if not show_raw:
        cmd.append("--no-show-raw-insn")
    cmd.append(str(obj_path))
    return subprocess.check_output(cmd, text=True)


def print_item_header(
    item: dict,
    code_name: str,
    raw_len: int,
    paths: tuple[Path, Path, Path],
    keep_files: bool,
    arch: str,
    target: str,
) -> None:
    location = item.get("file", "<no-file>")
    if item.get("line") is not None:
        location = f"{location}:{item['line']}"
    print(
        f"== n={item.get('n', '?')} id={item.get('id', '?')} "
        f"variant={item.get('variant', '?')} code={code_name} bytes={raw_len} "
        f"jsonl_line={item.get('_jsonl_line', '?')} =="
    )
    print(f"source: {location}")
    print(f"arch: {arch}")
    print(f"target: {target}")
    suffix = "" if keep_files else " (temporary; use --out-dir to keep)"
    print(f"raw: {paths[0]}{suffix}")
    print(f"asm: {paths[1]}{suffix}")
    print(f"obj: {paths[2]}{suffix}")
    print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Disassemble base64 AsmJit machine code blobs from a Simjit JSONL bundle."
    )
    parser.add_argument("jsonl", type=Path, help="JSONL bundle produced by --dump-json")
    parser.add_argument("--n", type=int, help="Select bundle item by numeric n field")
    parser.add_argument(
        "--id", help="Select bundle item by test id, for example nullable:86"
    )
    parser.add_argument("--suite", help="Select bundle item by suite")
    parser.add_argument(
        "--variant",
        help="Select bundle item by variant, for example x86-vector or arm-vector",
    )
    parser.add_argument("--code", choices=ASM_CODE_NAMES, default="asmjit")
    parser.add_argument(
        "--all-asmjit", action="store_true", help="Disassemble asmjit and asmjit_s"
    )
    parser.add_argument(
        "--out-dir", type=Path, help="Keep generated .bin/.s/.o files in this directory"
    )
    parser.add_argument(
        "--show-raw-insn",
        action="store_true",
        help="Show instruction bytes in objdump output",
    )
    parser.add_argument(
        "--arch",
        choices=("auto", "x86", "arm"),
        default="auto",
        help="Disassembly arch. Default: auto from item variant",
    )
    parser.add_argument("--target", help="Override clang target for wrapper object")
    parser.add_argument("--clang", default=os.environ.get("CLANG", "clang"))
    parser.add_argument(
        "--llvm-objdump", default=os.environ.get("LLVM_OBJDUMP", "llvm-objdump")
    )
    args = parser.parse_args()

    clang = need_tool(args.clang)
    llvm_objdump = need_tool(args.llvm_objdump)
    item = load_jsonl_item(args.jsonl, args.n, args.id, args.suite, args.variant)
    entries = code_entries(item, args.code, args.all_asmjit)
    arch, target, objdump_options = resolve_arch_config(item, args.arch, args.target)

    if args.out_dir is not None:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        work_dir_ctx = None
        work_dir = args.out_dir
    else:
        work_dir_ctx = tempfile.TemporaryDirectory(prefix="simjit-objdump-")
        work_dir = Path(work_dir_ctx.name)

    try:
        for entry in entries:
            code_name = entry["name"]
            symbol = sanitize_symbol(f"expr_{item.get('n', 'x')}_{code_name}")
            raw = base64.b64decode(entry["code"])
            paths = write_executable_object(raw, symbol, work_dir, clang, target, arch)
            print_item_header(
                item, code_name, len(raw), paths, args.out_dir is not None, arch, target
            )
            print(
                objdump(paths[2], llvm_objdump, args.show_raw_insn, objdump_options),
                end="",
            )
            print()
    finally:
        if work_dir_ctx is not None:
            work_dir_ctx.cleanup()


if __name__ == "__main__":
    main()
